site_name: Shadertastic
theme:
  name: material
  logo: logo512.png
  favicon: logo192.png
  custom_dir: theme_override
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - awesome-nav
  - mkdocs-video:
      video_muted: true
      video_controls: true
      css_style:
        width: "640px"
        height: "360px"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
